spring:
  application:
    name: demo-gateway
  #configuracion de spring-cloud-gateway
  cloud:
    gateway:
      routes:
          predicates:
            - Path=/api/** #ruta de acceso
server:
  port: 8090




#configurador de servidor de eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #wait-time-in-ms-when-sync-empty: 0


